name: oil_gid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  cached_network_image: ^3.4.1
  crypto: ^3.0.7
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  dropdown_search: ^6.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^3.1.0
  flutter_secure_storage: ^10.0.0
  flutter_slider_drawer: ^3.0.2
  font_awesome_flutter: ^10.12.0
  geolocator: ^14.0.2
  hive_flutter: ^1.1.0
  markdown_widget: ^2.3.2+8
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  yandex_mapkit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/marker.png
